workflows:
  android:
    name: Build NativeScript Android App
    max_build_duration: 60 # Max build time in minutes
    environment:
      vars:
        - key: "NODE_VERSION"
          value: "16.x"  # Use a stable version of Node.js
        - key: "NPM_VERSION"
          value: "8.19.2" # NPM 8.x is compatible with Node.js 16.x
        - key: "NS_VERSION"
          value: "8.4.0"  # A stable version of NativeScript CLI
    scripts:
      - name: Install Dependencies
        script: |
          # Install Node.js and NPM dependencies
          curl -fsSL https://deb.nodesource.com/setup_16.x | bash -  # Updated Node.js version
          apt-get install -y nodejs
          npm install -g nativescript@${NS_VERSION}  # Install NativeScript CLI at the specified version
          npm install  # Install the project-specific dependencies
          
          # Install only Android component of NativeScript
          ns component add @nativescript/android  # Install Android component
      - name: Build Android App
        script: |
          # Install required Android tools if not already installed
          ns doctor --android
          # Build the Android app in release mode
          ns build android --release
    artifacts:
      - build/android/**/*.apk  # Collect the Android APK file
    publishing:
      scripts:
        - name: Publish to Google Play (for Android)
          script: |
            # Publish the Android build to Google Play using Fastlane
            fastlane android beta
