workflows:
  native:
    name: Build NativeScript App
    max_build_duration: 60 # Max build time in minutes
    environment:
      vars:
        - key: "NODE_VERSION"
          value: "14"
        - key: "NPM_VERSION"
          value: "7.24.0"
    scripts:
      - name: Install Dependencies
        script: |
          # Install Node.js and NPM dependencies
          curl -sL https://deb.nodesource.com/setup_14.x | bash -
          apt-get install -y nodejs
          npm install -g nativescript
          npm install
      - name: Build iOS App
        script: |
          # Build the iOS app
          ns build ios --release --for-device
      - name: Build Android App
        script: |
          # Build the Android app
          ns build android --release
    artifacts:
      - build/ios/**/*.ipa
      - build/android/**/*.apk
    publishing:
      scripts:
        - name: Publish to TestFlight (for iOS)
          script: |
            # Publish the iOS build to TestFlight (use fastlane)
            fastlane ios beta
        - name: Publish to Google Play (for Android)
          script: |
            # Publish the Android build to Google Play (use fastlane)
            fastlane android beta
